dist: bionic

addons:
  apt:
    update: true

language: python
python:
  - "3.6"
  - "3.7"
env:
  - HTCONDOR_VERSION=8.8
  - HTCONDOR_VERSION=8.9

matrix:
  fast_finish: true

before_install:
  - curl https://research.cs.wisc.edu/htcondor/ubuntu/HTCondor-Release.gpg.key | sudo apt-key add -
  - echo "deb http://research.cs.wisc.edu/htcondor/ubuntu/${HTCONDOR_VERSION}/bionic bionic contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y --no-install-recommends htcondor

install:
  - pip install -r requirements-dev.txt
  - pip install .

before_script:
  - bash tests/_inf/start_condor.sh

script:
  - pytest --cov
